[workspace]

members = [
    "signalo",
    "traits",
    "filters",
    "pipes",
]

[replace]
"signalo:0.1.3" = { path = "signalo" }
"signalo_traits:0.1.2" = { path = "traits" }
"signalo_filters:0.1.5" = { path = "filters" }
"signalo_pipes:0.1.3" = { path = "pipes" }
