[workspace]

members = [
    "signalo",
    "traits",
    "filters",
    "pipes",
]

[replace]
"signalo:0.2.1" = { path = "signalo" }
"signalo_traits:0.2.2" = { path = "traits" }
"signalo_filters:0.3.1" = { path = "filters" }
"signalo_pipes:0.3.1" = { path = "pipes" }
