[package]
authors = ["Vincent Esche <regexident@gmail.com>"]
name = "signalo"
version = "0.1.0"

[dependencies]
num-integer = "0.1.36"
num-traits = ">=0.2.1"

[dependencies.fpa]
optional = true
fpa = "^0.1.0"
features = ["try-from"]

[dependencies.typenum]
optional = true
version = ">=1.10.0"

[dev-dependencies.nearly_eq]
nearly_eq = "^0.2.3"

[dependencies.missing_mpl]
version = "0.1.1"
optional = true

[features]
fixed-point = ["fpa", "typenum", "nearly_eq/use_fpa"]
default = ["std"]
std = []
nightly = []
nightly = ["missing_mpl"]
