[workspace]

members = [
    "signalo",
    "traits",
    "filters",
    "pipes",
]

[replace]
"signalo_traits:0.1.0" = { path = "traits" }
"signalo_filters:0.1.0" = { path = "filters" }
"signalo_pipes:0.1.1" = { path = "pipes" }
