[package]
authors = ["Vincent Esche <regexident@gmail.com>"]
categories = [
    "no-std",
    "embedded",
    "multimedia",
    "science",
    "algorithms",
]
description = "A collection of filters used in 'signalo' umbrella crate."
documentation = "https://docs.rs/svm"
keywords = [
    "dsp",
    "digital-signal",
    "signal-processing",
    "filters",
    "pipeline",
]
license = "MPL-2.0"
name = "signalo_filters"
readme = "README.md"
repository = "https://github.com/signalo/signalo"
homepage = "https://github.com/signalo/signalo/tree/master/filters"
version = "0.1.0"

[dependencies]
signalo_traits = "0.1.0"
arraydeque = ">=0.4.2"
num-integer = ">=0.1.36"
num-traits = ">=0.2.1"

[dependencies.typenum]
version = ">=1.10.0"
optional = true

[dependencies.missing_mpl]
version = "~0.1"
optional = true

[dev-dependencies]
nearly_eq = "~0.2.4"

[features]
default = ["std"]
std = []
nightly = ["missing_mpl"]
