[package]
authors = ["Vincent Esche <regexident@gmail.com>"]
categories = [
    "no-std",
    "embedded",
    "multimedia",
    "science",
    "algorithms",
]
description = "A collection of filters used in 'signalo' umbrella crate."
documentation = "https://docs.rs/svm"
homepage = "https://github.com/signalo/signalo/tree/master/filters"
keywords = [
    "dsp",
    "digital-signal",
    "signal-processing",
    "filters",
    "pipeline",
]
license = "MPL-2.0"
name = "signalo_filters"
readme = "README.md"
repository = "https://github.com/signalo/signalo"
version = "0.1.5"

[dependencies]
arraydeque = "~0.4"
num-traits = "~0.2"
signalo_traits = "~0.1"
generic-array = "~0.11"

[dependencies.missing_mpl]
optional = true
version = "~0.1"

[dependencies.typenum]
optional = true
version = "~1.10"

[dev-dependencies]
nearly_eq = "~0.2"
rand = "~0.4"

[features]
default = ["std"]
nightly = ["missing_mpl"]
std = []
