name: Other

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]

jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: apache/skywalking-eyes@a196742f472feaffafea537ce5a2a4c3c53a8de4 # v0.9.0
        with:
          log: info
          config: .github/configs/skywalking-eyes.yml
          token: "" # disables auto-commenting on PRs
