name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]
    paths-ignore:
      - "CHANGELOG.md"
            
jobs:
  info:
    name: Rust Info
    runs-on: ubuntu-latest
    steps:
      - name: Rustup Show
        shell: bash
        run: rustup show
      - name: Rustup Version
        shell: bash
        run: rustup --version
  
  check:
    name: Check (std)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Run `cargo check`
        run: cargo check
      - name: Run `cargo check --no-default-features`
        run: cargo check --no-default-features
      - name: Run `cargo check --all-features`
        run: cargo check --all-features
  
  check_no_std:
    name: Check (no_std)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: thumbv7em-none-eabihf
      - name: Run `cargo check …` on no-std target
        run: cargo check --target thumbv7em-none-eabihf
      
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src
      - name: Run `cargo test`
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Run `cargo fmt …`
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Run `cargo clippy …`
        run: cargo clippy -- -D warnings

  minimal_versions:
    name: Compile and test with minimal versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - name: Run `minimal-versions check`
        run: cargo minimal-versions check --workspace --all-features --tests --ignore-private -v
        continue-on-error: true

  msrv:
    name: Verify minimal supported rust version
    runs-on: ubuntu-latest
    # Disabled until the following issue gets resolved (current: v0.16.2):
    # https://github.com/foresterre/cargo-msrv/issues/1023
    #
    # Temove this line to re-enable the job:
    if: false
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@v1.15.1
      - name: Install cargo-msrv
        run: cargo binstall cargo-msrv@0.16.0-beta.21 --no-confirm --all-features
      - name: Run `cargo msrv --version`
        run: cargo msrv --version
      - name: Run `cargo msrv verify`
        run: cargo msrv verify
